### ISSUE TITLE
cannot find the RadeonResetBugFixService.exe file in your repo

### ISSUE THREAD

**Issue by dmuiX** [inga-lovinde/RadeonResetBugFix#7]
I cannot find the RadeonResetBugFixService.exe file in your repo.
Do I miss sth? 
Have you changed your repo?
Is there sth. I have to do like compile or anything to actually get the exe file from the folder??

**Comment by dmuiX** [comment]
Found answer to my question: Yes I have to compile it by myself.
Kind of did it know. There are some dependencies: 
```
https://dotnet.microsoft.com/en-us/download/dotnet-framework/thank-you/net472-developer-pack-offline-installer
winget install nuget
cd wherever that RadeonResetBugFix directory is 
nuget restore
dotnet restore
dotnet build
```
then the exe can be found in RadeonResetBugFix/RadeonResetBugFixService\bin\Debug\RadeonResetBugFixService.exe

**Comment by inga-lovinde** [comment]
No, you don't have to compile it yourself.

Only the source code is versioned and is in git, of course.
And the compiled binaries are available on the "Releases" page: https://github.com/inga-lovinde/RadeonResetBugFix/releases
